Repository CA-G12/API-Project-TariqSada-TariqHisham, pull requests merged in 2022-08, with the labels that each got.

#2 Done
  JS/DOM.js
  JS/main.js
  JS/test.js
  index.html
  style.css
Labels: approved

#5 3 main page style
  index.html
  style.css
Labels: approved

#7 6 make the fetch function
  JS/DOM.js
  JS/main.js
Labels: approved

#9 Edit html css
  index.html
  style.css
Labels: for-review

#11 10 edit main page structure
  index.html
  style.css
Labels: done

#12 improve Dom file and arranging main.js file
  JS/DOM.js
  JS/main.js
  JS/test.js
  images
  index.html
  style.css
Labels: approved

#14 13 edit style css
  index.html
  style.css
Labels: approved

#16 add a default value when reloading page
  JS/DOM.js
  JS/main.js
  index.html
  style.css
Labels: approved

#18 17 responsive tablet
  style.css
Labels: awaiting-review

#19 border radius will be 0 from 0px to 940px
  style.css
Labels: approved

#21 handle empty value
  JS/DOM.js
  index.html
  style.css
Labels: awaiting-review
